### PR TITLE
Issue #125. Remove non-sensible directory defaults for config active and staging.

### LINKED ISSUE #125: Default values make no sense for config directories
If you go to /admin/config/system/backup_migrate/export/advanced on a fresh install and expand one of the config related fieldsets, you'll see that "Exclude the following files or directories" contains:
```
backup_migrate
styles
css
js
ctools
less
```
These are the defaults for the files directory, but they make no sense for a directory, that's supposed to only contain json files and no nesting at all.

backup-settings-config-dir

While there may eventually be a use-case to exclude a JSON file (like backup_migrate.settings.json), I don't think, above values ever make sense.

The values are from includes/sources.filesource.inc (exclude_filepaths).

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes #125

### CODE REVIEW

**Comment by indigoxela** [comment]
Hm... if I run tests locally, they fail, too. Not exactly the same failures. On php 8.2 - which might be a little too new. Currently test in GHA run on 7.4.

**Comment by argiepiano** [comment]
Thanks @indigoxela. I'll check tests in 8.2. 

BTW these tests on GHA have been failing randomly - when I run them again they pass usually. The error this one shows is completely puzziling: `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.simpletest331674cache_entity_comment' doesn't
    exist: SHOW CREATE TABLE `simpletest331674cache_entity_comment`;`

**Comment by argiepiano** [comment]
I just ran all 3 backup_migrate tests locally on 8.2 based on the dev version and with this patch, and they are all passing for me. Perhaps you are using an older dev version? If you have the time to run those again locally at some point and find issues again, pls let me know.

I'm going to close and reopen this to run the GHA tests again.

**Comment by argiepiano** [comment]
Tests pass on reopening 🙄

**Comment by indigoxela** [comment]
> Tests pass on reopening

That's good. And bad. But currently good.

**Pull request merged**
