### PR TITLE
Issue #122. Use jquery trigger('load') instead of load()

### LINKED ISSUE #122: backup_migrate.js uses `load()` method, which is deprecated in jQuery 3
There used to be 2 `load()` methods in pre-jQuery 3. The one without parameters was equivalent to `trigger('load')`. The one with at least one parameter was used for ajax requests. jQuery 3 removed the one without parameters, meaning that the 3 instances of `load()` in `backup_migrate.js` are trying to use the ajax loading, with a subsequent error which stops other javascript stuff from running. 

The solution is to change those to `trigger('load');`

### PR DESCRIPTION
**Pull request by argiepiano**
Fixes #122

### CODE REVIEW

**Comment by argiepiano** [comment]
Retriggering tests...

Hmm, why do they keep failing on first try?

**Comment by argiepiano** [comment]
There must be something wrong with the GHA test setup. Tests pass fine on local, fail sometimes on GHA.

**Comment by indigoxela** [comment]
Hm, odd, there are two "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.simpletest488140XXXX' doesn't exist

**Comment by argiepiano** [comment]
Now they passed hmmm weird

**Pull request merged**
